# Generated by Django 3.0 on 2021-12-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="course",
            field=models.ManyToManyField(blank=True, null=True, to="courses.Course"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="course",
            field=models.ManyToManyField(blank=True, null=True, to="courses.Course"),
        ),
    ]
