# Generated by Django 3.0 on 2021-12-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_auto_20211222_1353"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="course",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="course",
        ),
        migrations.AlterField(
            model_name="lecture",
            name="presentation",
            field=models.FileField(upload_to="media/lecture/%Y/%m/%d"),
        ),
    ]
