# Generated by Django 3.0 on 2021-12-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_auto_20211224_2143"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="course",
            field=models.ManyToManyField(blank=True, null=True, to="courses.Course"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="course",
            field=models.ManyToManyField(blank=True, null=True, to="courses.Course"),
        ),
    ]
