# Generated by Django 3.0 on 2021-12-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_auto_20211224_2235"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="students",
        ),
        migrations.RemoveField(
            model_name="course",
            name="teachers",
        ),
        migrations.AddField(
            model_name="student",
            name="course",
            field=models.ManyToManyField(blank=True, null=True, to="courses.Course"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="course",
            field=models.ManyToManyField(blank=True, null=True, to="courses.Course"),
        ),
    ]
