# Generated by Django 3.0 on 2021-12-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_auto_20211225_0003"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="homework_question",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
