# Generated by Django 3.0 on 2021-12-29 00:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_auto_20211228_2248"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="score",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
