version: "3"

services:
  web:
    restart: always
    build: ./src/backend
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=lever_x
      - POSTGRES_PASSWORD=lever_x
      - POSTGRES_DB=lever_x
volumes:
  postgres_data: